[package]
name = "rotntake/blood-engine"
version = "0.1.3"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
licence = "MIT"
authors = ["rotntake"]

description = "A droplet emitter system."

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml"]

[dev-dependencies]

[dependencies]
